Hozkada/Hozkada/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HozkadaBokatak.urls')),
    # path('HozkadaBokatak/', include('django.contrib.auth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hozkada/HozkadaBokatak/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name = 'index'), 

    path('bokatak/', views.bokatak, name = 'bokatak'),

    path('gehitubezeroa/', views.register_bezeroa, name='register_user'),
    path('gehitubezeroa/gehitubezeroaerregistroa/', views.register_bezeroa_erregistroa, name='registerbezeroaerregistroa'),

    path('perfil/', views.perfil, name='perfil'),
    path('perfil/updatebezeroa/<id>', views.update_bezeroa, name="updatebezeroa"),

    path('bokatak/agregar_bocata_al_carrito/<int:platerra_id>/', views.agregar_bocata_al_carrito, name='agregar_bocata_al_carrito'),

    path('bokatak/lista_carrito/', views.lista_carrito, name='lista_carrito'),

    path('bokatak/actualizar_cantidad/', views.actualizar_cantidad, name='actualizar_cantidad'),

    path('bokatak/eliminar_del_carrito/', views.eliminar_del_carrito, name='eliminar_del_carrito'),

    path('bokatak/marcar_eskaera_completada/', views.marcar_eskaera_completada, name='marcar_eskaera_completada'),

    

    path('eskaera/', views.eskaera, name='eskaera'),

    path('login_user', views.login_user, name='login'),
    path('logout_user', views. logout_user, name='logout'),

    #AJUSTES
    path('ezarpenak/', views.ezarpenak, name='ezarpenak'),
    path('lista_bezeroak/', views.lista_bezeroak, name='lista_bezeroak'),
    path('crear_bezeroa/', views.crear_bezeroa, name='crear_bezeroa'),
    path('editar_bezeroa/<int:id>/', views.editar_bezeroa, name='editar_bezeroa'),
    path('eliminar_bezeroa/<int:id>/', views.eliminar_bezeroa, name='eliminar_bezeroa'),
    path('obtener_datos_bezeroa/<int:id>/', views.obtener_datos_bezeroa, name='obtener_datos_bezeroa'),




    path('lista_platerrak/', views.lista_platerrak, name='lista_platerrak'),
    path('crear_platerra/', views.crear_platerra, name='crear_platerra'),
    path('editar_platerra/<int:id>/', views.editar_platerra, name='editar_platerra'),
    path('eliminar_platerra/<int:id>/', views.eliminar_platerra, name='eliminar_platerra'),
    path('obtener_datos_platerra/<int:id>/', views.obtener_datos_platerra, name='obtener_datos_platerra'),
]

Hozkada/HozkadaBokatak/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Bezeroa(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nan = models.CharField(max_length=10)
    izena = models.CharField(max_length=20)
    abizena = models.CharField(max_length=20)
    abizena2 = models.CharField(max_length=20)
    telefonoa = models.CharField(max_length=20)
    emaila = models.EmailField(max_length=50, default='')
    helbidea = models.CharField(max_length=100)
    postakodea = models.CharField(max_length=10)
    bidalketaKostua = models.FloatField(default=0)
    img = models.ImageField(upload_to='img/erabiltzaileak')

    def __str__(self):
        return self.izena

class Platerra(models.Model):
    motak = (
        ('haragia', 'Haragia'),
        ('arraina', 'Arraina'),
        ('begetarianoa', 'Begetarianoa'),
        ('beganoa', 'Beganoa'),
         ('edaria', 'Edaria'),
    )
    izena = models.CharField(max_length=100)
    deskribapena = models.CharField(max_length=1000)
    prezioa = models.FloatField(default=0)
    mota = models.CharField(max_length=20, choices=motak, default='haragia')
    img = models.ImageField(upload_to='img/bokatak')
    alergiak = models.ManyToManyField('Alergia', blank=True)

    def precio_con_descuento(self):
        deskontua_set = self.deskontua_platerra_set.all()
        print("Deskontua_Platerra instances:", deskontua_set)
        deskontua = deskontua_set.first()  # Suponiendo que solo hay un descuento por plato
        if deskontua:
            descuento_porcentaje = deskontua.deskontua_id.ehunekoa
            precio_descuento = self.prezioa - (self.prezioa * descuento_porcentaje / 100)
            return round(precio_descuento, 2)
        else:
            return self.prezioa

    def __str__(self):
        return self.izena

class Eskaera(models.Model):
    id_bezeroa = models.ForeignKey(Bezeroa, on_delete=models.CASCADE)
    eskaera_data = models.DateField(default=timezone.now)
    egoera = models.BooleanField(default=True)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
       return f"{self.id} - {self.id_bezeroa}"

class Platerra_Eskaera(models.Model):
    eskaera_id = models.ForeignKey(Eskaera, on_delete=models.CASCADE)
    platerra_id = models.ForeignKey(Platerra, on_delete=models.CASCADE)
    kantitatea = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.eskaera_id} - {self.platerra_id}"

class Alergia(models.Model):
    izena = models.CharField(max_length=30)
    img = models.ImageField()

    def __str__(self):
        return self.izena

class Deskontua(models.Model):
    izena = models.CharField(max_length=50)
    ehunekoa = models.FloatField(default=0)
    kantitatea = models.IntegerField(default=0)

    def __str__(self):
        return self.izena

class Deskontua_Platerra(models.Model):
    platerra_id = models.ForeignKey(Platerra, on_delete=models.CASCADE)
    deskontua_id = models.ForeignKey(Deskontua, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.platerra_id} - {self.deskontua_id}"

class Alergia_Platerra(models.Model):
    platerra_id = models.ForeignKey(Platerra, on_delete=models.CASCADE)
    alergia_id = models.ForeignKey(Alergia, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.alergia_id} - {self.platerra_id}"

Hozkada/HozkadaBokatak/forms.py
# forms.py
from django import forms
from .models import Bezeroa, Platerra

class BezeroaForm(forms.ModelForm):
    class Meta:
        model = Bezeroa
        fields = '__all__'

class PlaterraForm(forms.ModelForm):
    class Meta:
        model = Platerra
        fields = '__all__'

Hozkada/HozkadaBokatak/views.py
from datetime import datetime, timezone
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect,reverse
from .models import Platerra
from .models import Alergia_Platerra, Eskaera, Platerra_Eskaera
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from .models import Platerra
from.models import User
from .models import Bezeroa
from .models import Alergia_Platerra
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm

from HozkadaBokatak.models import Bezeroa



# Create your views here.



def index(request): 
    return render(request, 'index.html')

def bokatak(request):
    platerra = Platerra.objects.all
    alergia_platerrak = Alergia_Platerra.objects.all
    return render(request, 'bokatak.html', {'bokatak':platerra,'alergia_platerrak':alergia_platerrak})

def register_bezeroa(request):
    return render(request, 'register_user.html')

def register_bezeroa_erregistroa(request):
    if request.method == 'POST':
        username = request.POST['username']
        nan = request.POST['nan']
        izena = request.POST['izena']
        abizena = request.POST['abizena']
        abizena2 = request.POST['abizena2']
        telefonoa = request.POST['telefonoa']
        emaila = request.POST['email']
        pasahitza = request.POST['pasahitza']
        helbidea = request.POST['helbidea']
        postakodea = request.POST['pk']
        argazkia = request.FILES['argazkia']
        bidalketaKostua = request.POST['bidalketaKostua']

        # Create a User instance
        user = User.objects.create_user(username=username, email=emaila, password=pasahitza)
        
        # Create a Bezeroa instance linked to the user
        bezeroa = Bezeroa(
            user=user,  # Link the Bezeroa model to the user
            nan=nan,
            izena=izena,
            abizena=abizena,
            abizena2=abizena2,
            telefonoa=telefonoa,
            emaila=emaila,
            helbidea=helbidea,
            postakodea=postakodea,
            img = argazkia,
            bidalketaKostua = bidalketaKostua
        )

        bezeroa.save()
        return HttpResponseRedirect(reverse('index'))
    
def perfil(request):
    return render(request, 'perfil.html')

@login_required
def update_bezeroa(request, id):
    if request.method == 'POST':
        izena = request.POST['izena']
        abizena = request.POST['abizena']
        abizena2 = request.POST['abizena2']
        nan = request.POST['nan']
        telefonoa = request.POST['telefonoa']
        emaila = request.POST['email']
        helbidea = request.POST['helbidea']
        postalkodea = request.POST['pk']
        username = request.POST['username']
        bidalketaKostua = request.POST['bidalketaKostua']
        bezeroa = Bezeroa.objects.get(user_id=id)

        if 'argazkia' in request.FILES:
            argazkia = request.FILES['argazkia']
            bezeroa.img = argazkia


        bezeroa.izena = izena
        bezeroa.abizena = abizena
        bezeroa.abizena2 = abizena2
        bezeroa.nan = nan
        bezeroa.telefonoa = telefonoa
        bezeroa.emaila = emaila
        bezeroa.helbidea = helbidea
        bezeroa.postakodea = postalkodea
        bezeroa.bidalketaKostua = bidalketaKostua
        bezeroa.save()
        # Guardar los cambios en la base de datos

        user = User.objects.get(id=id)
        user.username = username
        user.save()

        # Redireccionar a la página 'index'
        return HttpResponseRedirect(reverse('index'))

#  Con esta funcion estoy tratando de crear una nueva escaera y al mismo tiempo crear un nuevo platerra_eskaera
@login_required
def agregar_bocata_al_carrito(request,platerra_id): 

    # Obtén el usuario actual y verifica si ya tiene una Eskaera activa
    user = request.user
    eskaera = Eskaera.objects.filter(id_bezeroa=user.bezeroa, egoera=False).first()

    # Si no existe una Eskaera activa, crea una nueva
    if not eskaera:
        eskaera = Eskaera(id_bezeroa=user.bezeroa, egoera=False)
        eskaera.save()
    # Obten el platerra seleccionado por su id
    platerra = Platerra.objects.get(id=platerra_id)

    # Ahora, crea o actualiza la relación Platerra_Eskaera
    platerra_eskaera, created = Platerra_Eskaera.objects.get_or_create(eskaera_id=eskaera, platerra_id=platerra)

    #Aumenta la cantidad en 1
    platerra_eskaera.kantitatea += 1
    platerra_eskaera.save()

     # Guarda la información del carrito en la sesión del usuario
    request.session['carrito'] = list(Platerra_Eskaera.objects.filter(eskaera_id=eskaera).values('platerra_id__izena', 'kantitatea'))
    # Devuelve una respuesta JSON
    response_data = {"success": True,"platerra_nombre": platerra.izena}  # Cambia a False si hay un error
    
    return JsonResponse(response_data)


@login_required
def marcar_eskaera_completada(request):
    try:
        user = request.user
        eskaera = Eskaera.objects.filter(id_bezeroa=user.bezeroa, egoera=False).first()

        if eskaera:
            eskaera.egoera = True
            eskaera.save()

            response_data = {"success": True}
        else:
            response_data = {"success": False, "error": "No hay Eskaera activa"}

        return JsonResponse(response_data)
    except Exception as e:
        print(e)
        response_data = {"success": False, "error": str(e)}
        return JsonResponse(response_data)



@login_required
def lista_carrito(request):
    # Obtén los elementos del carrito
    elementos_carrito = Platerra_Eskaera.objects.filter(
        eskaera_id__id_bezeroa=request.user.bezeroa,
        eskaera_id__egoera=False
    )

    # Prepara los datos a mostrar en el div
    carrito_data = [{"id": elemento.id,"izena": elemento.platerra_id.izena, "kantitatea": elemento.kantitatea,"prezioa":elemento.platerra_id.precio_con_descuento()} for elemento in elementos_carrito]

    # Crea una respuesta JSON con los datos del carrito
    response_data = {
        'carrito_data': carrito_data,
    }

    return JsonResponse(response_data)


@login_required
def actualizar_cantidad(request):
    if request.method == 'POST':
        platerra_nombre = request.POST.get('platerra_nombre')
        nueva_cantidad = request.POST.get('nueva_cantidad')

        # Obtiene el precio unitario del Platerra
        platerra = Platerra.objects.get(izena=platerra_nombre)
        precio_unitario = platerra.precio_con_descuento()

        print("Precio Unitario:", precio_unitario)


        # Actualiza la cantidad en la base de datos según el nombre del platerra
        Platerra_Eskaera.objects.filter(
            eskaera_id__id_bezeroa=request.user.bezeroa,
            eskaera_id__egoera=False,
            platerra_id__izena=platerra_nombre
        ).update(kantitatea=nueva_cantidad)

        response_data = {
            "success": True,
            "precio_unitario": precio_unitario
        }
        return JsonResponse(response_data)
    else:
        response_data = {"success": False, "redirect": reverse('login')}
        return JsonResponse(response_data)
    

@login_required
def eliminar_del_carrito(request):
    platerra_eskaera_id = request.POST.get('platerra_eskaera_id', None)
    print("Entrando en eliminar_del_carrito")
    
    print("Platerra Eskaera ID:", platerra_eskaera_id)

    if platerra_eskaera_id is not None and platerra_eskaera_id != 'undefined':
        # Utiliza directamente get_object_or_404 sin especificar id=id
        platerra_eskaera = Platerra_Eskaera.objects.get(id=platerra_eskaera_id)


        # Elimina el platerra_eskaera
        platerra_eskaera.delete()

        # Devuelve una respuesta JSON
        response_data = {"success": True}  # Cambia a False si hay un error
    else:
        response_data = {"success": False, "error": "platerra_eskaera_id no proporcionado en la solicitud"}

    return JsonResponse(response_data)



@login_required
def eskaera(request):
    print("ENTRANDO EN ESKAERA")
    eskaeras = Eskaera.objects.filter(id_bezeroa=request.user.bezeroa).order_by('-data')

    # Calcula el total para cada Eskaera
    for eskaera in eskaeras:
        eskaera.total = sum(
            platerra_eskaera.kantitatea * platerra_eskaera.platerra_id.precio_con_descuento()
            for platerra_eskaera in Platerra_Eskaera.objects.filter(eskaera_id=eskaera)
        )
        eskaera.time_difference = calculate_time_difference(eskaera.data)

    return render(request, 'eskaera.html', {'eskaeras': eskaeras})



def calculate_time_difference(date):
    # Asegúrate de que date sea un objeto datetime con información de zona horaria
    if date.tzinfo is None:
        date = date.replace(tzinfo=timezone.utc)

    now = datetime.now(timezone.utc)
    difference = now - date
    days = difference.days
    hours, remainder = divmod(difference.seconds, 3600)
    minutes, _ = divmod(remainder, 60)

    if days > 0:
        if hours > 0:
            return f"{days} {'Egun' if days == 1 else 'Egun'} {hours} {'Ordu' if hours == 1 else 'Ordu'}"
        else:
            return f"{days} {'Egun' if days == 1 else 'Egun'}"
    elif hours > 0:
        return f"{hours} {'Ordu' if hours == 1 else 'Ordu'}"
    elif minutes > 0:
        return f"{minutes} {'minutu' if minutes == 1 else 'minutu'}"
    else:
        return "Oraintxe bertan"


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

Hozkada/HozkadaBokatak/templates/eskaera.html
<!DOCTYPE html>
<html lang="eu">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Koulen"
    />
    <!-- KoulenFont -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <!-- bootstrap -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <link rel="stylesheet" href="../static/eskaera.css" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>

    <title>Eskaerak</title>

    <style>
      .eskaera-btn {
        color: orange;
        font-size: 36px;
      }

      .eskaera-btn.collapsed {
        color: orange; /* Color cuando está colapsado */
      }

      .eskaera-btn:not(.collapsed):hover {
        color: darkorange; /* Color cuando está expandido y se hace hover */
      }

      .eskaera-content {
        border: none; /* Elimina el borde azul cuando se abre */
      }

      .eskaera-content ul {
        list-style: none;
        padding: 0;
      }

      .eskaera-content li {
        color: #e2ad5c;
        font-size: 20px;
      }

      .eskaera-content p {
        color: purple;
        font-size: 28px;
      }

      .eskaera-content p:last-child {
        color: #e2ad5c;
        font-size: 24px;
      }
    </style>
  </head>
  <body>
    <div id="navbar">
      <a href=""><img id="logo" src="../static/media/logo.png" alt="" /></a>
      <div id="links">
        <a class="link" href="{% url 'index'%}">Hasiera</a>
        <a class="link" href="{% url 'bokatak'%}">Bokatak</a>
      </div>
      <div id="username-txt" class="dropdown">
        <p>{{user.username}}</p>
        <div class="dropdown-content">
          <a href="{% url 'perfil' %}">PERFILA</a>
          <a href="{% url 'eskaera' %}">ESKAERA</a>
          <a href="{% url 'logout' %}">SESIOA ITXI</a>
          <!-- Agrega más enlaces según tus necesidades -->
        </div>
      </div>
      <div id="profile-picture">
        <img src="{{user.bezeroa.img.url}}" alt="Foto de perfil" />
      </div>
    </div>
    <br /><br /><br /><br /><br /><br />
    <h1 style="text-align: center; color: black; font-size: 36px">
      Zure eskaerak
    </h1>
    <div id="content">
      <div id="eskaeracontent">
        {% for eskaera in eskaeras %}
        <div class="eskaera">
          <button
            class="btn btn-link eskaera-btn"
            data-toggle="collapse"
            data-target="#eskaera{{ forloop.counter }}"
          >
            <h2 style="font-size: 36px">
              Eskaera #{{ forloop.counter }} -
              <span style="font-size: 25px"
                >Orain dela {{ eskaera.time_difference }}</span
              >
            </h2>
          </button>
          <div
            id="eskaera{{ forloop.counter }}"
            class="collapse eskaera-content"
          >
            <ul>
              {% for platerra_eskaera in eskaera.platerra_eskaera_set.all %}
              <li>
                {{ platerra_eskaera.platerra_id.izena }} - Kantitatea:
                <span style="color: blue"
                  >{{ platerra_eskaera.kantitatea }}</span
                >
                - Prezioa:
                <span style="color: green"
                  >{{ platerra_eskaera.platerra_id.precio_con_descuento}}€</span
                >
              </li>
              {% endfor %}
            </ul>
            <p class="total">Guztira: {{ eskaera.total }}€</p>
            {% if not eskaera.egoera %}
            <p style="color: #e2ad5c; font-size: 24px">
              Oraindik ez duzu eskatu eskaera hau ;D
            </p>
            {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    <br /><br />
    <div id="footer">
      <div id="Logo">
        <a href=""
          ><img id="logofooter" src="../static/media/logo.png" alt=""
        /></a>
      </div>
      <div id="Linkak">
        <h3>Linkak</h3>
        <ul>
          <li><a href="#">Faq</a></li>
          <li><a href="#">Estilo Gida</a></li>
          <li><a href="#">Laguntza</a></li>
          <li><a href="#">Bidaltze Politikak</a></li>
        </ul>
      </div>
      <div id="Kontaktua">
        <h3>Kontaktua</h3>
        <ul>
          <li><a>Eibar, Azpizuri Kalea 24, 20600</a></li>
          <li><a>HozkadaDenda@gmail.com</a></li>
          <li><a>+34 634 95 74 16</a></li>
          <li><a>+34 634 49 96 55</a></li>
        </ul>
      </div>
      <div id="Sozialak">
        <h3>Sare Sozialak</h3>
        <ul>
          <li>
            <a href="#"><i class="fab fa-facebook social-icon"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-twitter social-icon"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-instagram social-icon"></i></a>
          </li>
        </ul>
      </div>
    </div>

    <script>
      $(document).ready(function () {
        $(".eskaera-btn").click(function () {
          $(".eskaera-btn").not(this).removeClass("collapsed");
          $(".collapse").not($(this).next()).removeClass("show");
        });
      });
    </script>
  </body>
</html>

Hozkada/HozkadaBokatak/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="../static/media/nav_ico.png" type="image/png" />
    <link rel="stylesheet" href="../static/index.css" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Koulen"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />

    <title>Hozkada</title>
  </head>
  <body>
    <div id="navbar">
      <a href=""><img id="logo" src="../static/media/logo.png" alt="" /></a>
      <div id="links">
        <a class="link" href="">Hasiera</a>
        <a class="link" href="/bokatak">Bokatak</a>
        {% if user.is_staff %}
      <a class="link" href="/ezarpenak">Ezarpenak</a>
    {% endif %}
      </div>
      {% if user.is_authenticated %}
      <div id="username-txt" class="dropdown">
        <p>{{user.username}}</p>
        <div class="dropdown-content">
          <a href="{% url 'perfil' %}">PERFILA</a>
          <a href="{% url 'eskaera' %}">ESKAERA</a>
          <a href="{% url 'logout' %}">SESIOA ITXI</a>
        </div>
      </div>
      <div id="profile-picture">
        <img src="{{user.bezeroa.img.url}}" alt="Foto de perfil" />
      </div>

      {% else %}
      <div class="sartu">
        <a class="sartuinp" href="{%url 'login'%}">Sartu</a>
        <a class="sartuinp" href="gehitubezeroa/">Erregistratu</a>
      </div>
      {% endif %}
    </div>

    <div id="goiburua">
      <a href="bokatak/"
        ><img id="eskaera" src="../static/media/index_img/Eskaera.png"
      /></a>
      <img
        src="../static/media/index_img/goiburua.png"
        alt=""
        style="width: 100%"
      />
      <h3 id="titulo-hozkada">Hozkada</h3>
    </div>

    <div id="contenido1">
      <div class="izquierda">
        <img
          src="../static/media/index_img/bar-cola.jpg"
          alt="Imagen izquierda"
        />
      </div>
      <div class="derecha">
        <p id="nortzuk">Nortzuk Gara</p>
        <br /><br />
        Lorem ipsum dolor sit amet consectetur adipiscing, elit arcu facilisi
        imperdiet interdum conubia ornare, dis integer rutrum nisl sociosqu
        faucibus, non penatibus maecenas senectus ultrices. Nec vestibulum
        ullamcorper nullam orci hac praesent, pharetra ridiculus maecenas
        parturient mus natoque, blandit sociis justo in malesuada. Aliquet
        accumsan platea morbi dis at hac auctor faucibus nascetur in, a feugiat
        leo mus conubia integer cursus aptent condimentum. Primis iaculis ju
      </div>
    </div>

    <div id="contenido">
      <div class="izquierda2">
        <p id="zer">Zer Egiten Dugu</p>
        <br /><br />
        Lorem ipsum dolor sit amet consectetur adipiscing, elit arcu facilisi
        imperdiet interdum conubia ornare, dis integer rutrum nisl sociosqu
        faucibus, non penatibus maecenas senectus ultrices. Nec vestibulum
        ullamcorper nullam orci hac praesent, pharetra ridiculus maecenas
        parturient mus natoque, blandit sociis justo in malesuada. Aliquet
        accumsan platea morbi dis at hac auctor faucibus nascetur in, a feugiat
        leo mus conubia integer cursus aptent condimentum. Primis iaculis ju
      </div>
      <div class="derecha2">
        <img
          src="../static/media/index_img/bocadilloshaciendo.jpg"
          alt="Imagen izquierda"
        />
      </div>
    </div>

    <div id="contenido">
      <div class="imagenfinal">
        <img
          src="../static/media/index_img/imagenfinal.jpg"
          alt="Imagen izquierda"
        />
      </div>
    </div>

    <div id="footer">
      <div id="Logo">
        <a href=""
          ><img id="logofooter" src="../static/media/logo.png" alt=""
        /></a>
      </div>
      <div id="Linkak">
        <h3>Linkak</h3>
        <ul>
          <li><a href="#">Faq</a></li>
          <li><a href="#">Estilo Gida</a></li>
          <li><a href="#">Laguntza</a></li>
          <li><a href="#">Bidaltze Politikak</a></li>
        </ul>
      </div>
      <div id="Kontaktua">
        <h3>Kontaktua</h3>
        <ul>
          <li><a>Eibar, Azpizuri Kalea 24, 20600</a></li>
          <li><a>HozkadaDenda@gmail.com</a></li>
          <li><a>+34 634 95 74 16</a></li>
          <li><a>+34 634 49 96 55</a></li>
        </ul>
      </div>
      <div id="Sozialak">
        <h3>Sare Sozialak</h3>
        <ul>
          <li>
            <a href="#"><i class="fab fa-facebook social-icon"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-twitter social-icon"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-instagram social-icon"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </body>
</html>